# SPDX-License-Identifier: Apache-2.0
---

- name: Examine the OS minor version, RHEL
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_fact_ansible_distribution_minor_version: '{{ ansible_distribution_version.split(".")[1] }}'

- name: Find all RHEL vars files
  ansible.builtin.find:
    paths:
      - "{{ role_path }}/vars"
    recurse: false
    patterns: "RedHat_{{ ansible_distribution_major_version }}*plus.yml"
  delegate_to: localhost
  register: __sap_hana_preconfigure_fact_find_result_rhel_minor_plus_vars_files

# Note: vars files for RHEL minor plus versions: vars files for certain RHEL minor versions which are also valid
# for all later RHEL minor versions
- name: Create a dict containing the additional vars files for the current RHEL minor version or later
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_fact_rhel_minor_plus_vars_files_dict: >-
      {{ __sap_hana_preconfigure_fact_rhel_minor_plus_vars_files_dict | d([])
         + [{'minor_version': (__sap_hana_preconfigure_vars_files_line_item.split('/')[-1].split('.')[-3] | int),
           'filename': __sap_hana_preconfigure_vars_files_line_item }]
      }}
  loop: "{{ __sap_hana_preconfigure_fact_find_result_rhel_minor_plus_vars_files.files | map(attribute='path') }}"
  loop_control:
    loop_var: __sap_hana_preconfigure_vars_files_line_item

- name: Numerically sort the list of dicts by the RHEL minor version
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_fact_rhel_minor_plus_vars_files_dict_sorted: "{{ __sap_hana_preconfigure_fact_rhel_minor_plus_vars_files_dict | sort(attribute='minor_version') }}"

- name: Create the final list of additional vars files for the current RHEL minor version or later
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_fact_rhel_minor_plus_vars_files_sorted: >-
      {{ __sap_hana_preconfigure_fact_rhel_minor_plus_vars_files_sorted | d([])
         + [__sap_hana_preconfigure_vars_files_dict_line_item.filename]
      }}
  loop: "{{ __sap_hana_preconfigure_fact_rhel_minor_plus_vars_files_dict_sorted }}"
  loop_control:
    loop_var: __sap_hana_preconfigure_vars_files_dict_line_item

- name: Display the list of additional vars files
  ansible.builtin.debug:
    var: __sap_hana_preconfigure_fact_rhel_minor_plus_vars_files_sorted

- name: Include additional RHEL specific vars, valid for the current RHEL minor version or later
  ansible.builtin.include_vars:
    file: "{{ __rhel_minor_plus_vars_file_line_item }}"
  loop: "{{ __sap_hana_preconfigure_fact_rhel_minor_plus_vars_files_sorted }}"
  loop_control:
    loop_var: __rhel_minor_plus_vars_file_line_item
    label: "{{ __rhel_minor_plus_vars_file_line_item.split('/')[-1] }}"
  when:
    - (__rhel_minor_plus_vars_file_line_item.split('/')[-1]).split('.')[-3] | int
      <= __sap_hana_preconfigure_fact_ansible_distribution_minor_version | int
    - lookup('file', __rhel_minor_plus_vars_file_line_item, errors='ignore') is not none
