# SPDX-License-Identifier: Apache-2.0
---

# SAP System IDs that are reserved and must not be used
# Reference: SAP Note 1979280
__sap_hana_install_sid_prohibited: ['ADD', 'ADM', 'ALL', 'AMD', 'AND', 'ANY', 'ARE', 'ASC', 'AUX', 'AVG', 'BIN', 'BIT', 'CDC', 'COM', 'CON', 'DAA', 'DBA', 'DBM', 'DBO', 'DTD', 'ECO', 'END', 'EPS', 'EXE', 'FOR', 'GET', 'GID', 'IBM', 'INT', 'KEY', 'LIB', 'LOG', 'LPT', 'MAP', 'MAX', 'MEM', 'MIG', 'MIN', 'MON', 'NET', 'NIX', 'NOT', 'NUL', 'OFF', 'OLD', 'OMS', 'OUT', 'PAD', 'PRN', 'RAW', 'REF', 'ROW', 'SAP', 'SET', 'SGA', 'SHG', 'SID', 'SQL', 'SUM', 'SYS', 'TMP', 'TOP', 'TRC', 'UID', 'USE', 'USR', 'VAR']

__sap_hana_install_fact_tmp_dirname: ''

# This dictionary defines keyword rules to identify SAP binaries compatible with modern Linux distributions supported by SAP HANA.
# Each key is a valid `ansible_architecture` value.
# The value is a list of rule sets, where each rule set is a list of keywords.
# A file is considered a match if all keywords from any single rule set are found in the `file` command's output.
__sap_hana_install_architecture_matrix:
  x86_64:
    # LINUX ON X86_64 64BIT
    # Requires 'ELF' and 'Linux' to differentiate from other x86-64 binaries like those for Solaris (also ELF) or Windows (PE format).
    # Example: SAPCAR_1400-70007716.EXE: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked,
    # interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.4, BuildID[sha1]=52b9652252273d4c212fa366935ea3152244ead4, not stripped
    - ['x86-64', 'ELF', 'Linux']
    # If ELF is UNIX - System V, then check for interpreter linux string.
    - ['x86-64', 'ELF', 'SYSV', 'linux']
  ppc64le:
    # LINUX ON POWER LE 64BIT
    # 'LSB' (Least Significant Bit) is crucial to identify Little-Endian PowerPC, as opposed to the older Big-Endian 'MSB' (Most Significant Bit) variant.
    # Example: SAPCAR_1400-70007726.EXE: ELF 64-bit LSB shared object, 64-bit PowerPC or cisco 7500, OpenPOWER ELF V2 ABI, version 1 (GNU/Linux), dynamically linked,
    # interpreter /lib64/ld64.so.2, for GNU/Linux 3.0.0, BuildID[sha1]=52ce4823a8d2273a2bc15d7c8161a24d65b4223f, not stripped
    - ['PowerPC', 'LSB']
  s390x:
    # LINUX ON ZSERIES 64BIT
    # Identifies binaries for Linux on IBM Z & LinuxONE systems.
    # Example: SAPCAR_1400-70007722.EXE: ELF 64-bit MSB shared object, IBM S/390, version 1 (SYSV), dynamically linked,
    # interpreter /lib/ld64.so.1, for GNU/Linux 2.6.4, BuildID[sha1]=a31118ae8d69bf9422b86930012a6c5776cbc82d, not stripped
    - ['IBM S/390']
  aarch64:
    # LINUX ON ARM 64BIT
    # Identifies binaries for the 64-bit Arm architecture.
    # Example: SAPCAR_1400-80008313.EXE: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked,
    # interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=f40042b59e928aacfff753e59686be4d6e242998, for GNU/Linux 3.7.0, not stripped
    - ['aarch64']
