# SPDX-License-Identifier: Apache-2.0
---

# can be configured by tuned profile sap-hana, entry "force_latency=70"
- name: Add boot command line args for configuring C-States for lower latency
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_boot_command_line_args_final: >-
      {{ __sap_hana_preconfigure_boot_command_line_args_final | d('') + __sap_hana_preconfigure_boot_command_line_args['c-states']['args'] + ' ' }}
  notify: __sap_hana_preconfigure_grubby_update_handler
  changed_when: true
  when:
    - ansible_architecture in __sap_hana_preconfigure_boot_command_line_args['c-states']['arch']
  tags: grubconfig
