# SPDX-License-Identifier: Apache-2.0
---

# can be configured by tuned profile sap-hana, entry "force_latency=70"
- name: Add boot command line args for configuring C-States for lower latency
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_boot_command_line_args_final: >-
      {{ __sap_hana_preconfigure_boot_command_line_args_final + [__sap_hana_preconfigure_kernel_arg_line_item] }}
  loop: "{{ sap_hana_preconfigure_boot_command_line_args['c-states']['args'] }}"
  loop_control:
    loop_var: __sap_hana_preconfigure_kernel_arg_line_item
  when:
    - sap_hana_preconfigure_boot_command_line_args['c-states']['arch'] is defined
    - ansible_architecture in sap_hana_preconfigure_boot_command_line_args['c-states']['arch']
