# SPDX-License-Identifier: Apache-2.0
---

- name: Add boot command line args for configuring TSX
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_boot_command_line_args_final: >-
      {{ __sap_hana_preconfigure_boot_command_line_args_final + [__sap_hana_preconfigure_kernel_arg_line_item] }}
  loop: "{{ __sap_hana_preconfigure_boot_command_line_args['tsx']['args'] }}"
  loop_control:
    loop_var: __sap_hana_preconfigure_kernel_arg_line_item
  when:
    - ansible_architecture in __sap_hana_preconfigure_boot_command_line_args['tsx']['arch']
    - ansible_distribution_major_version | int >= 9 or
      (ansible_distribution_major_version == '8' and
       __sap_hana_preconfigure_fact_ansible_distribution_minor_version | int >= 3)
