# SPDX-License-Identifier: Apache-2.0
---

- name: Display the role path
  ansible.builtin.debug:
    var: role_path

# Load variable files in order:
# 1. Suse.yml / RedHat.yml - Specific to OS family.
# 2. SLES_15.yml / RedHat_9.yml - Specific to distribution (SLES, SLES_SAP or RedHat) and major release.
# 3. SLES_15.6.yml / RedHat_9.2 - Specific to distribution (SLES, SLES_SAP or RedHat) and minor release.
# 4. SLES_SAP_15.yml - Specific to distribution SLES_SAP and major release.
# 5. SLES_SAP_15.6.yml - Specific to distribution SLES_SAP and minor release.
- name: Include OS specific vars, specific
  ansible.builtin.include_vars: "{{ __vars_file }}"
  loop: "{{ __var_files }}"
  vars:
    __vars_file: "{{ role_path }}/vars/{{ item }}"
    __distribution_major: "{{ ansible_distribution ~ '_' ~ ansible_distribution_major_version }}"
    __distribution_major_minor: "{{ ansible_distribution ~ '_' ~ ansible_distribution_version }}"
    # Enables loading of shared vars between SLES and SLES_SAP
    __distribution_major_split: "{{ ansible_distribution.split('_')[0] ~ '_' ~ ansible_distribution_major_version }}"
    __distribution_major_minor_split: "{{ ansible_distribution.split('_')[0] ~ '_' ~ ansible_distribution_version }}"
    __var_files: >-
      {{
        [
          ansible_os_family ~ '.yml',
          (ansible_distribution ~ '.yml') if ansible_distribution != ansible_os_family else None,
          (__distribution_major_split ~ '.yml') if __distribution_major_split != __distribution_major else None,
          (__distribution_major_minor_split ~ '.yml') if __distribution_major_minor_split != __distribution_major_minor else None,
          __distribution_major ~ '.yml',
          __distribution_major_minor ~ '.yml',
        ] | select('defined') | select('string') | list
      }}
  when: __vars_file is file

- name: Examine the OS minor version, RHEL
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_fact_ansible_distribution_minor_version: '{{ ansible_distribution_version.split(".")[1] }}'
  when: ansible_distribution == 'RedHat'

- name: Include additional RHEL specific vars, minor version or lower
  ansible.builtin.include_vars:
    file: "{{ __vars_file }}"
  loop: "{{ range(0, 11) }}"
  loop_control:
    loop_var: __minor_release_line_item
    label: "{{ __vars_file.split('/')[-1] }}"
  vars:
    __vars_file: >-
      {{ role_path }}/vars/{{ ansible_distribution ~ '_' ~ ansible_distribution_major_version ~ '.' ~ __minor_release_line_item ~ '.plus' ~ '.yml' }}
  when:
    - ansible_distribution == 'RedHat'
    - __minor_release_line_item <= __sap_hana_preconfigure_fact_ansible_distribution_minor_version | int
    - lookup('file', __vars_file, errors='ignore') is not none

- name: Set filename prefix to empty string if role is run in normal mode
  ansible.builtin.set_fact:
    assert_prefix: ""
  when: not sap_hana_preconfigure_assert | d(false)

- name: Prepend filename with assert string if role is run in assert mode
  ansible.builtin.set_fact:
    assert_prefix: "assert-"
  when: sap_hana_preconfigure_assert | d(false)

- name: Display the content of sap_general_preconfigure_fact_reboot_required
  ansible.builtin.debug:
    var: sap_general_preconfigure_fact_reboot_required

- name: Include installation.yml
  ansible.builtin.include_tasks: '{{ item }}/{{ assert_prefix }}installation.yml'
  when: sap_hana_preconfigure_config_all | d(true) or sap_hana_preconfigure_installation | d(false)
  with_first_found:
    - '{{ ansible_distribution.split("_")[0] }}'
    - '{{ ansible_distribution }}'

- name: Include configuration.yml
  ansible.builtin.include_tasks: '{{ item }}/{{ assert_prefix }}configuration.yml'
  when: sap_hana_preconfigure_config_all | d(true) or sap_hana_preconfigure_configuration | d(false)
  with_first_found:
    - '{{ ansible_distribution.split("_")[0] }}'
    - '{{ ansible_distribution }}'

# allow a reboot at the end of the preconfigure role
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
