# SPDX-License-Identifier: Apache-2.0
---

# yamllint disable rule:commas rule:colons
__sap_hana_preconfigure_boot_command_line_args:
# SAP NOTE 3108302:
# RHEL 9.0 and later:
  c-states: { arch: ['x86_64'],            args: ['processor.max_cstate=1', 'intel_idle.max_cstate=1'] }
  tsx:      { arch: ['x86_64'],            args: ['tsx=on'] }
# RHEL 9.2 and later:
  thp:      { arch: ['x86_64', 'ppc64le'], args: ['transparent_hugepage=madvise'] }
# yamllint enable rule:commas rule:colons
