# SPDX-License-Identifier: Apache-2.0
---

__sap_hana_preconfigure_packages:
# SAP NOTE 3108316:
  - expect
# package gtk2: only needed if the SAP HANA installation tools hdblcmgui and hdbsetup are used
  - gtk2
  - krb5-workstation
  - libatomic
  - libcanberra-gtk2
  - libtool-ltdl
  - numactl
  - PackageKit-gtk3-module
  - xorg-x11-xauth
# package chkconfig: needed by hdblcm to be able to access /etc/init.d
  - chkconfig
# package compat-openssl11: needed for HANA scale-out and when configuring HANA backup on Azure
  - compat-openssl11
# package libxcrypt-compat: needed SAP HANA and also by sapstartsrv on RHEL 9:
#  - libxcrypt-compat       # now installed by role sap_general_preconfigure, see also SAP note 3108316, version 4.
# For support purposes:
# package graphwiz: graph visualization tools, for supportability)
  - graphviz
# package iptraf-ng: TCP/IP network monitor, for supportability)
  - iptraf-ng
# package lm-sensors: TCP/IP network monitor, for supportability)
  - lm_sensors
# package nfs-utils: support utilities for NFS, for supportability)
  - nfs-utils
# SAP NOTE 3108302:
  - tuned-profiles-sap-hana

__sap_hana_preconfigure_packages_min_install:
# SAP NOTE 3108316:
  - expect
# package gtk2: only needed if the SAP HANA installation tools hdblcmgui and hdbsetup are used
#  - gtk2
  - krb5-workstation
  - libatomic
  - libcanberra-gtk2
  - libtool-ltdl
  - numactl
  - PackageKit-gtk3-module
  - xorg-x11-xauth
# package compat-openssl11: needed for HANA scale-out and when configuring HANA backup on Azure
  - compat-openssl11
# required for SAP HANA on RHEL 9:
  - libxcrypt-compat
# For support purposes:
# package graphwiz: graph visualization tools, for supportability)
#  - graphviz
# package iptraf-ng: TCP/IP network monitor, for supportability)
#  - iptraf-ng
# package lm-sensors: TCP/IP network monitor, for supportability)
#  - lm_sensors
# package nfs-utils: support utilities for NFS, for supportability)
#  - nfs-utils
# SAP NOTE 3108302:
  - tuned-profiles-sap-hana
