# SPDX-License-Identifier: Apache-2.0
---
# SAP HANA Database SID in capital letters (String). Example: 'H02'
sap_ha_install_hana_hsr_sid: "{{ sap_hana_sid | upper }}"

# SAP HANA Database Instance Number (String). Example: '90'
sap_ha_install_hana_hsr_instance_number: "{{ sap_hana_instance_number }}"

# Dictionary with cluster nodes. Same dictionary is used by LSR ha_cluster.
# sap_hana_cluster_nodes:
#   - node_name: "hana0"
#     node_ip: "10.0.0.1"
#     node_role: primary
#     hana_site: DC01
#   - node_name: "hana1"
#     node_ip: "10.0.0.2"
#     node_role: secondary
#     hana_site: DC02
sap_ha_install_hana_hsr_cluster_nodes: "{{ sap_hana_cluster_nodes }}"

# Name of database user for backups (String).
sap_ha_install_hana_hsr_hdbuserstore_system_backup_user: HDB_SYSTEMDB

# Master password for database (String).
sap_ha_install_hana_hsr_db_system_password: "{{ sap_hana_install_master_password }}"

# Fully qualified domain name (String).
sap_ha_install_hana_hsr_fqdn: "{{ sap_domain }}"

# HSR Replication mode (String).
sap_ha_install_hana_hsr_rep_mode: sync

# HSR Operation mode (String).
sap_ha_install_hana_hsr_oper_mode: logreplay

# Set to true to update /etc/hosts (Boolean).
sap_ha_install_hana_hsr_update_etchosts: true

# Define the directory path where database backup will be created (String).
# Required sub-directories will be created in this path: SYSTEMDB and DB_<SID>.
# Default: /usr/sap/<SID>/HDB<INST_NR>/backup/data/
# Backup will be created with name: <SID>_PRE_HSR_<TIMESTAMP> (e.g. H02_PRE_HSR_20250729_1426)
# sap_ha_install_hana_hsr_backup_path: ''
