# SPDX-License-Identifier: Apache-2.0
---
# SAP NetWeaver ABAP specific parameter values
#
# TODO: make sure to first respect 'ha_cluster' native variables

# Extra package list is combination of:
#  minimal base packages required for all scenarios
#  scenario specific packages
#  halib package if selected
__sap_ha_pacemaker_cluster_sap_extra_packages: "{{
  __sap_ha_pacemaker_cluster_sap_extra_packages_dict.minimal | d([])
  + __sap_ha_pacemaker_cluster_sap_extra_packages_dict.nwas | unique }}"

# SUSE Specific: Combine list of zypper patterns
__sap_ha_pacemaker_cluster_sap_zypper_patterns: "{{
  __sap_ha_pacemaker_cluster_sap_zypper_patterns_dict.minimal | d([])
  + __sap_ha_pacemaker_cluster_sap_zypper_patterns_dict.nwas | d([]) }}"
