# SPDX-License-Identifier: Apache-2.0
---
# Variables specific to following versions:
# - SUSE Linux Enterprise Server for SAP Applications 15
# - SUSE Linux Enterprise Server 15

__sap_ha_pacemaker_cluster_sap_extra_packages_dict:
  minimal:
    - ClusterTools2
  hana_scaleout:
    - SAPHanaSR-ScaleOut
  hana_scaleup:
    - SAPHanaSR
  hana_angi:
    - SAPHanaSR-angi
  nwas:
    - sap-suse-cluster-connector
    - sapstartsrv-resource-agents

# Dictionary with zypper patterns for specific scenarios
__sap_ha_pacemaker_cluster_sap_zypper_patterns_dict:
  minimal:
    - ha_sles
  hana_scaleout: []
  hana_scaleup: []
  nwas: []
