# SPDX-License-Identifier: Apache-2.0
---

# List of required packages to install
__sap_anydb_install_oracle_packages:
  - csh
  - ksh
  - mksh
  - bc
  - bind-utils
  - gcc
  - gcc-c++
  - glibc-devel
  - libcap
  - libaio
  - libaio-devel
  - libgcc
  - libstdc++
  - libstdc++-devel
  - make
  - psmisc
  - rdma-core-devel
  - smartmontools
  - sysstat
  - unzip
  - xorg-x11-utils
  - xorg-x11-xauth
  - unixODBC
  - unixODBC-devel
  - libnsl
