# SPDX-License-Identifier: Apache-2.0
---
# Reminder: This file is included in a loop over a dictionary.
# Included in: tasks/include_construct_vip_resources.yml
#
# file loop var: vip_list_item
#
# Example:
# {{ vip_list_item.key }}   => vip_SID_00_primary
# {{ vip_list_item.value }} => 192.168.1.10

- name: "SAP HA Prepare Pacemaker - Add resource: VIP {{ vip_list_item.key }} (IPaddr2)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__resource_vip] }}"
  vars:
    __ipaddr_ip:
      - name: ip
        value: "{{ vip_list_item.value | quote }}"
    # Create separate list for nic parameter only when it is defined and not empty.
    __ipaddr_nic:
      - name: nic
        value: "{{ sap_ha_pacemaker_cluster_vip_client_interface | d('') }}"

    __resource_vip:
      id: "{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents['ipaddr'].agent }}"
      instance_attrs:
        # Combine both lists if sap_ha_pacemaker_cluster_vip_client_interface is defined and not empty.
        - attrs: "{{ __ipaddr_ip + __ipaddr_nic
            if sap_ha_pacemaker_cluster_vip_client_interface is defined and sap_ha_pacemaker_cluster_vip_client_interface | length > 0
            else __ipaddr_ip }}"
  when:
    - vip_list_item.key not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - sap_ha_pacemaker_cluster_vip_method == 'ipaddr' or
      (__sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].with is defined and
       __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].with == 'ipaddr')
